name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:

  CD:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v4.1.1

      - name: Autenticar no GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER }}
          location: ${{ secrets.GKE_REGION }}

      - name: Deploy to GKE
        run: |
          kubectl apply -f ./kube-news/k8s/deployment.yaml
