name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Login no Docker hub
        run: echo "docker login"
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
        username: ${{secrets.DOCKERHUB_USER}}
        password: ${{secrets.DOCKERHUB_PWD}}
      - name: Construir a imagem do container
        run: echo "docker build"
      - name: Subir imagem no docker registry
        run: echo "docker push"
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - name: Autenticar na AWS
        run: echo "Autenticar na AWS"
      - name: Configurar Kubeconfig
        run: echo "Configurar Kubeconfig"
      - name: Aplicar o deploy
        run: echo "kubectl apply"
