name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v4.1.1
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}
      - name: Build and push Docker images
        uses: docker/build-push-action@v5.0.0
        with:
          context: ./kube-news/src
          file: ./kube-news/src/Dockerfile
          push: true
          tags: |
            leolessa10/kube-news:${{ github.run_number }}
            leolessa10/kube-news:latest

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v4.1.1
      - name: Autenticar no GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configurar gcloud
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Configurar Kubeconfig
        run: |
          gcloud container clusters get-credentials nome-do-cluster --zone us-central1-a

      - name: Instalar kubectl
        run: |
          sudo apt-get update
          sudo apt-get install -y kubectl

      - name: Deploy to GKE using kubectl
        run: |
          kubectl apply -f ./kube-news/k8s/deployment.yaml
