name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - nome: Construir a imagem do container
      run: echo "docker build"
      - nome: Login no Docker hub
      run: echo "docker login"
      - nome: Subir imagem no docker registry
      run: echo "docker push"
  CD:
    runs-on: ubuntu-latest
    steps:
    - nome: Autenticar na AWS
      run: echo "Autenticar na AWS"
      - nome: Configurar Kubeconfig
      run: echo "Configurar Kubeconfig"
      - nome: Aplicar o deploy
      run: echo "kubectl apply"
